### ISSUE TITLE
phpunit test risky error:

### ISSUE THREAD

**Issue by moodlebeuth** [unirz-tu-ilmenau/moodle-block_opencast#65]
Hello,
I've got the following "risky" error message during the phpunit test:

Moodle 3.5.1+ (Build: 20180831), ref: refs/heads/MOODLE_351+_STABLE
Php: 7.0.30.0.9.1, pgsql: 10.5 (Debian 10.5-1.pgdg90+1), OS: Linux 4.17.0-0.bpo.3-amd64 x86_64
PHPUnit 6.5.12 by Sebastian Bergmann and contributors.

1) block_opencast_upload_testcase::test_upload
This test printed output: proceed: 577000
Job failed due to: moodle_exception: Username for Opencast API user is not setup correctly, go to settings of block opencast to fix this in /var/www/moodle/admin/tool/opencast/classes/local/api.php:93
Stack trace:
#0 /var/www/moodle/blocks/opencast/classes/local/apibridge.php(466): tool_opencast\local\api->__construct()
#1 /var/www/moodle/blocks/opencast/classes/local/apibridge.php(499): block_opencast\local\apibridge->create_course_series('157000')
#2 /var/www/moodle/blocks/opencast/classes/local/upload_helper.php(304): block_opencast\local\apibridge->ensure_course_series_exists('157000')
#3 /var/www/moodle/blocks/opencast/classes/local/upload_helper.php(432): block_opencast\local\upload_helper->process_upload_job(Object(stdClass))
#4 /var/www/moodle/blocks/opencast/tests/upload_test.php(79): block_opencast\local\upload_helper->cron()
#5 [internal function]: block_opencast_upload_testcase->test_upload()
#6 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestCase.php(1071): ReflectionMethod->invokeArgs(Object(block_opencast_upload_testcase), Array)
#7 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestCase.php(939): PHPUnit\Framework\TestCase->runTest()
#8 /var/www/moodle/lib/phpunit/classes/advanced_testcase.php(80): PHPUnit\Framework\TestCase->runBare()
#9 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestResult.php(698): advanced_testcase->runBare()
#10 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(block_opencast_upload_testcase))
#11 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /var/www/moodle/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /var/www/moodle/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(546): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /var/www/moodle/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#16 /var/www/moodle/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#17 /var/www/moodle/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#18 {main}

Please could you have a look at this error.

Cheers,
Michael

**Comment by tobiasreischmann** [comment]
Hey Michael,
indeed there is a bug in the reference to the config. The config values are now stored at tool_opencast instead of block_opencast. However, this test case can not be considered as actual test case as used by Continuous Integration Systems. For the test case to run successfully, you have to setup an opencast instance and set the url, username and password accordingly.
However, I will change the config access as described.
Cheers Tobias
